export enum ActivityType {
  APPOINTMENT_COMPLETED = "APPOINTMENT_COMPLETED",
  APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED",
  APPOINTMENT_BOOKED = "APPOINTMENT_BOOKED",
  PRESCRIPTION_CREATED = "PRESCRIPTION_CREATED",
  WALLET_CREDITED = "WALLET_CREDITED",
  NEW_REVIEW_RECEIVED = "NEW_REVIEW_RECEIVED",
}

export interface RecentActivityItem {
  type: ActivityType;
  title: string;
  description: string;
  createdAt: string;
}
